### ISSUE TITLE
erro "no CUDA-capable device is detected"

### ISSUE THREAD

**Issue by puneetjindal** [endernewton/tf-faster-rcnn#235]
error while running CUDA_VISIBLE_DEVICES=${GPU_ID} ./tools/demo.py

I am developing everything in this image with nvidia grid k520

Following are the details
if I run nvidia-smi      
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.81                 Driver Version: 384.81                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GRID K520           Off  | 00000000:00:03.0 Off |                  N/A |
| N/A   25C    P8    18W / 125W |     11MiB /  4036MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

What can be the issue?

**Comment by endernewton** [comment]
did you install the gpu version of tf?

**Comment by CheungXu** [comment]
Did you set the right GPU_ID? It should be 0 if you only have one GPU. I met the same error when I forget execute command "GPU_ID=0" before testing.

**Comment by engineer1109** [comment]
Please export your cuda path manually when you run by other account
or pip install TensorFlow-gpu

**Comment by quaner2557** [comment]
I solved it by rebooting
